spec-version: 0.36.0
name:         drasil-testing-kit
version:      0.0.1
author:       "Jason Balaci, Daniel Jarabek, Jacques Carette, Spencer Smith"
maintainer:   "Jacques Carette"
synopsis:     A framework for code and document generation for scientific software
github:       JacquesCarette/Drasil
homepage:     https://jacquescarette.github.io/Drasil/
description:  Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

language: Haskell2010
default-extensions:
- ImportQualifiedPost
- StrictData

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- directory
- drasil-file-handling
- filepath
- process
- tasty

ghc-options:
- -Wall
- -Wredundant-constraints
- -Wmissing-export-lists

library:
  source-dirs: lib
  exposed-modules:
  - Drasil.TestingKit.FileHandling
  - Drasil.TestingKit.GoldenTesting
  - Drasil.TestingKit.TestMain
