## \file Constants.py
# \author Thulasi Jegatheesan
# \brief Provides the structure for holding constant values
# \note Generated by Drasil v0.1-alpha

## \brief Structure for holding the constant values
class Constants:
    PI = 3.14159265
    L_MIN = 0.1
    L_MAX = 50.0
    RHO_W_MIN = 950.0
    RHO_W_MAX = 1000.0
    A_C_MAX = 100000.0
    C_W_MIN = 4170.0
    C_W_MAX = 4210.0
    H_C_MIN = 10.0
    H_C_MAX = 10000.0
    T_FINAL_MAX = 86400.0
    AR_MIN = 1.0e-2
    AR_MAX = 100.0
