## \file Constants.py
# \author Thulasi Jegatheesan
# \brief Provides the structure for holding constant values
# \Generated by Drasil v0.1-alpha
## \brief Structure for holding the constant values
class Constants:
    pi = 3.14159265
    L_min = 0.1
    L_max = 50.0
    rho_W_min = 950.0
    rho_W_max = 1000.0
    A_C_max = 100000.0
    C_W_min = 4170.0
    C_W_max = 4210.0
    h_C_min = 10.0
    h_C_max = 10000.0
    t_final_max = 86400.0
    AR_min = 1.0e-2
    AR_max = 100.0
