package BSS;

/** \file Constants.java
    \author Xinlu Yan
    \brief Provides the structure for holding constant values
    \note Generated by Drasil v0.1-alpha
*/

/** \brief Structure for holding the constant values
*/
public class Constants {
    public static final double G = 6.6743e-11;
    public static final double m_min = 1.0e29;
    public static final double m_max = 1.0e32;
    public static final double r_max = 1.0e13;
    public static final double v_max = 1000000.0;
    public static final double t_max = 1.0e10;
    
}
