package BSS;

/** \file InputParameters.java
    \author Xinlu Yan
    \brief Provides the function for reading inputs and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class InputParameters {
    
    /** \brief Reads input from a file with the given file name
        \param filename name of the input file
        \return array containing the following values:
        \return mass of the first star (kg)
        \return mass of the second star (kg)
        \return initial x-position of the first star (m)
        \return initial y-position of the first star (m)
        \return initial x-position of the second star (m)
        \return initial y-position of the second star (m)
        \return initial x-velocity of the first star (m/s)
        \return initial y-velocity of the first star (m/s)
        \return initial x-velocity of the second star (m/s)
        \return initial y-velocity of the second star (m/s)
        \return final time (s)
    */
    public static Object[] get_input(String filename) throws FileNotFoundException {
        double m_1;
        double m_2;
        double x_1_0;
        double y_1_0;
        double x_2_0;
        double y_2_0;
        double v_x1_0;
        double v_y1_0;
        double v_x2_0;
        double v_y2_0;
        double t_final;
        
        Scanner infile;
        infile = new Scanner(new File(filename));
        infile.nextLine();
        m_1 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        m_2 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_1_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_1_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        x_2_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        y_2_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_x1_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_y1_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_x2_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        v_y2_0 = Double.parseDouble(infile.nextLine());
        infile.nextLine();
        t_final = Double.parseDouble(infile.nextLine());
        infile.close();
        
        Object[] outputs = new Object[11];
        outputs[0] = m_1;
        outputs[1] = m_2;
        outputs[2] = x_1_0;
        outputs[3] = y_1_0;
        outputs[4] = x_2_0;
        outputs[5] = y_2_0;
        outputs[6] = v_x1_0;
        outputs[7] = v_y1_0;
        outputs[8] = v_x2_0;
        outputs[9] = v_y2_0;
        outputs[10] = t_final;
        return outputs;
    }
    
    /** \brief Verifies that input values satisfy the physical constraints and software constraints
        \param m_1 mass of the first star (kg)
        \param m_2 mass of the second star (kg)
        \param x_1_0 initial x-position of the first star (m)
        \param y_1_0 initial y-position of the first star (m)
        \param x_2_0 initial x-position of the second star (m)
        \param y_2_0 initial y-position of the second star (m)
        \param v_x1_0 initial x-velocity of the first star (m/s)
        \param v_y1_0 initial y-velocity of the first star (m/s)
        \param v_x2_0 initial x-velocity of the second star (m/s)
        \param v_y2_0 initial y-velocity of the second star (m/s)
        \param t_final final time (s)
    */
    public static void input_constraints(double m_1, double m_2, double x_1_0, double y_1_0, double x_2_0, double y_2_0, double v_x1_0, double v_y1_0, double v_x2_0, double v_y2_0, double t_final) {
        if (!(Constants.m_min <= m_1 && m_1 <= Constants.m_max)) {
            System.out.print("Warning: ");
            System.out.print("m_1 has value ");
            System.out.print(m_1);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(Constants.m_min);
            System.out.print(" (m_min)");
            System.out.print(" and ");
            System.out.print(Constants.m_max);
            System.out.print(" (m_max)");
            System.out.println(".");
        }
        if (!(Constants.m_min <= m_2 && m_2 <= Constants.m_max)) {
            System.out.print("Warning: ");
            System.out.print("m_2 has value ");
            System.out.print(m_2);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(Constants.m_min);
            System.out.print(" (m_min)");
            System.out.print(" and ");
            System.out.print(Constants.m_max);
            System.out.print(" (m_max)");
            System.out.println(".");
        }
        if (!(-Constants.r_max <= x_1_0 && x_1_0 <= Constants.r_max)) {
            System.out.print("Warning: ");
            System.out.print("x_1_0 has value ");
            System.out.print(x_1_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.r_max);
            System.out.print(" (-r_max)");
            System.out.print(" and ");
            System.out.print(Constants.r_max);
            System.out.print(" (r_max)");
            System.out.println(".");
        }
        if (!(-Constants.r_max <= y_1_0 && y_1_0 <= Constants.r_max)) {
            System.out.print("Warning: ");
            System.out.print("y_1_0 has value ");
            System.out.print(y_1_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.r_max);
            System.out.print(" (-r_max)");
            System.out.print(" and ");
            System.out.print(Constants.r_max);
            System.out.print(" (r_max)");
            System.out.println(".");
        }
        if (!(-Constants.r_max <= x_2_0 && x_2_0 <= Constants.r_max)) {
            System.out.print("Warning: ");
            System.out.print("x_2_0 has value ");
            System.out.print(x_2_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.r_max);
            System.out.print(" (-r_max)");
            System.out.print(" and ");
            System.out.print(Constants.r_max);
            System.out.print(" (r_max)");
            System.out.println(".");
        }
        if (!(-Constants.r_max <= y_2_0 && y_2_0 <= Constants.r_max)) {
            System.out.print("Warning: ");
            System.out.print("y_2_0 has value ");
            System.out.print(y_2_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.r_max);
            System.out.print(" (-r_max)");
            System.out.print(" and ");
            System.out.print(Constants.r_max);
            System.out.print(" (r_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_x1_0 && v_x1_0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_x1_0 has value ");
            System.out.print(v_x1_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_y1_0 && v_y1_0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_y1_0 has value ");
            System.out.print(v_y1_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_x2_0 && v_x2_0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_x2_0 has value ");
            System.out.print(v_x2_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(-Constants.v_max <= v_y2_0 && v_y2_0 <= Constants.v_max)) {
            System.out.print("Warning: ");
            System.out.print("v_y2_0 has value ");
            System.out.print(v_y2_0);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(-Constants.v_max);
            System.out.print(" (-v_max)");
            System.out.print(" and ");
            System.out.print(Constants.v_max);
            System.out.print(" (v_max)");
            System.out.println(".");
        }
        if (!(t_final <= Constants.t_max)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("below ");
            System.out.print(Constants.t_max);
            System.out.print(" (t_max)");
            System.out.println(".");
        }
        
        if (!(m_1 > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("m_1 has value ");
            System.out.print(m_1);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(m_2 > 0.0)) {
            System.out.print("Warning: ");
            System.out.print("m_2 has value ");
            System.out.print(m_2);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
        if (!(t_final >= 0.0)) {
            System.out.print("Warning: ");
            System.out.print("t_final has value ");
            System.out.print(t_final);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0);
            System.out.println(".");
        }
    }
}
