package BSS;

/** \file ODE.java
    \author Xinlu Yan
    \brief Class representing an ODE system
    \note Generated by Drasil v0.1-alpha
*/

import org.apache.commons.math3.ode.FirstOrderDifferentialEquations;

/** \brief Class representing an ODE system
*/
public class ODE implements FirstOrderDifferentialEquations {
    private double m_1;
    private double m_2;
    private double x_1_0;
    private double y_1_0;
    private double x_2_0;
    private double y_2_0;
    private double v_x1_0;
    private double v_y1_0;
    private double v_x2_0;
    private double v_y2_0;
    private double t_final;
    
    /** \brief Constructor for ODE objects
        \param m_1 mass of the first star (kg)
        \param m_2 mass of the second star (kg)
        \param x_1_0 initial x-position of the first star (m)
        \param y_1_0 initial y-position of the first star (m)
        \param x_2_0 initial x-position of the second star (m)
        \param y_2_0 initial y-position of the second star (m)
        \param v_x1_0 initial x-velocity of the first star (m/s)
        \param v_y1_0 initial y-velocity of the first star (m/s)
        \param v_x2_0 initial x-velocity of the second star (m/s)
        \param v_y2_0 initial y-velocity of the second star (m/s)
        \param t_final final time (s)
    */
    public ODE(double m_1, double m_2, double x_1_0, double y_1_0, double x_2_0, double y_2_0, double v_x1_0, double v_y1_0, double v_x2_0, double v_y2_0, double t_final) {
        this.m_1 = m_1;
        this.m_2 = m_2;
        this.x_1_0 = x_1_0;
        this.y_1_0 = y_1_0;
        this.x_2_0 = x_2_0;
        this.y_2_0 = y_2_0;
        this.v_x1_0 = v_x1_0;
        this.v_y1_0 = v_y1_0;
        this.v_x2_0 = v_x2_0;
        this.v_y2_0 = v_y2_0;
        this.t_final = t_final;
    }
    
    /** \brief returns the ODE system dimension
        \return dimension of the ODE system
    */
    public int getDimension() {
        return 8;
    }
    
    /** \brief function representation of an ODE system
        \param t current independent variable value in ODE solution
        \param q dependent variables (m)
        \param dq change in dependent variables (m)
    */
    public void computeDerivatives(double t, double[] q, double[] dq) {
        dq[0] = q[4];
        dq[1] = q[5];
        dq[2] = q[6];
        dq[3] = q[7];
        dq[4] = -6.6743e-11 * m_2 * (q[0] - q[2]) / Math.pow(Math.sqrt(Math.pow(q[0] - q[2], 2.0) + Math.pow(q[1] - q[3], 2.0)), 3.0);
        dq[5] = -6.6743e-11 * m_2 * (q[1] - q[3]) / Math.pow(Math.sqrt(Math.pow(q[0] - q[2], 2.0) + Math.pow(q[1] - q[3], 2.0)), 3.0);
        dq[6] = 6.6743e-11 * m_1 * (q[0] - q[2]) / Math.pow(Math.sqrt(Math.pow(q[0] - q[2], 2.0) + Math.pow(q[1] - q[3], 2.0)), 3.0);
        dq[7] = 6.6743e-11 * m_1 * (q[1] - q[3]) / Math.pow(Math.sqrt(Math.pow(q[0] - q[2], 2.0) + Math.pow(q[1] - q[3], 2.0)), 3.0);
    }
}
