/** Calculations.swift
    Provides functions for calculating the outputs
    - Authors: Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    - Note: Generated by Drasil v0.1-alpha
*/

import Foundation

/** Calculates flight duration (s)
    - Parameter inParams: structure holding the input values
    - Parameter g: magnitude of gravitational acceleration (m/s^2)
    - Returns: flight duration (s)
*/
func func_t_flight(_ inParams: inout InputParameters, _ g: Double) -> Double {
    return 2.0 * inParams.v_launch * sin(inParams.theta) / g
}

/** Calculates landing position (m)
    - Parameter inParams: structure holding the input values
    - Parameter g: magnitude of gravitational acceleration (m/s^2)
    - Returns: landing position (m)
*/
func func_p_land(_ inParams: inout InputParameters, _ g: Double) -> Double {
    return 2.0 * pow(inParams.v_launch, 2.0) * sin(inParams.theta) * cos(inParams.theta) / g
}

/** Calculates distance between the target position and the landing position (m)
    - Parameter inParams: structure holding the input values
    - Parameter p_land: landing position (m)
    - Returns: distance between the target position and the landing position (m)
*/
func func_d_offset(_ inParams: inout InputParameters, _ p_land: Double) -> Double {
    return p_land - inParams.p_target
}
