/** \file Control.cs
    \author Olu Owojaiye
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void Main(string[] args) {
        string filename = args[0];
        double L_rod;
        double m;
        double α;
        double θ_p;
        double θ_i;
        double p_x^i;
        double p_y^i;
        InputParameters.get_input(filename, out L_rod, out m, out α, out θ_p, out θ_i);
        InputParameters.derived_values(L_rod, θ_i, out p_x^i, out p_y^i);
        InputParameters.input_constraints(L_rod, θ_i);
        OutputFormat.write_output(θ_p);
    }
}
