/** \file Constants.hpp
    \author Thulasi Jegatheesan
    \brief Provides the structure for holding constant values
    \Generated by Drasil v0.1-alpha
*/
#ifndef Constants_h
#define Constants_h

/** \brief Structure for holding the constant values
*/
class Constants {
    public:
        static const double pi;
        static const double L_min;
        static const double L_max;
        static const double rho_W_min;
        static const double rho_W_max;
        static const double A_C_max;
        static const double C_W_min;
        static const double C_W_max;
        static const double h_C_min;
        static const double h_C_max;
        static const double t_final_max;
        static const double AR_min;
        static const double AR_max;
        
};

#endif
