## \file Calculations.py
# \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
# \brief Provides functions for calculating the outputs
# \note Generated by Drasil v0.1-alpha

import math

## \brief Calculates flight duration (s)
# \param v_launch launch speed (m/s)
# \param theta launch angle (rad)
# \param g magnitude of gravitational acceleration (m/s^2)
# \return flight duration (s)
def func_t_flight(v_launch, theta, g):
    return 2.0 * v_launch * math.sin(theta) / g

## \brief Calculates landing position (m)
# \param v_launch launch speed (m/s)
# \param theta launch angle (rad)
# \param g magnitude of gravitational acceleration (m/s^2)
# \return landing position (m)
def func_p_land(v_launch, theta, g):
    return 2.0 * v_launch ** 2.0 * math.sin(theta) * math.cos(theta) / g

## \brief Calculates distance between the target position and the landing position (m)
# \param p_target target position (m)
# \param p_land landing position (m)
# \return distance between the target position and the landing position (m)
def func_d_offset(p_target, p_land):
    return p_land - p_target
