/** \file Constants.cs
    \author Xinlu Yan
    \brief Provides the structure for holding constant values
    \note Generated by Drasil v0.1-alpha
*/

/** \brief Structure for holding the constant values
*/
public class Constants {
    public const double G = 6.6743e-11;
    public const double m_min = 1.0e29;
    public const double m_max = 1.0e32;
    public const double r_max = 1.0e13;
    public const double v_max = 1000000.0;
    public const double t_max = 1.0e10;
    
}
