""" VectorTest.jl
    Tests native vector operations.
    - Authors: Drasil
    - Note: Generated by Drasil v0.1-alpha
"""

module VectorTest

import LinearAlgebra

function vectorOps(a::Array{Float64}, b::Array{Float64})
    made = [1.0, 2.0, 3.0]
    scaled = 2.0 * a
    summed = a + b
    elem = a[1]
    dotted = LinearAlgebra.dot(a, b)
    dim = length(a)
    mag = LinearAlgebra.norm(a)
    unit = a / LinearAlgebra.norm(a)
    combo1 = 2.0 * a + b
    combo2 = 2.0 * (a + b)
    return dotted
end

end
