% VectorTest.m
% Tests native vector operations.
% - Authors: Drasil
% - Note: Generated by Drasil v0.1-alpha

function result = vectorOps(a, b)
    scaled = 2.0 * a;
    summed = a + b;
    elem = a(1);
    dotted = dot(a, b);
    result = dotted;
end
