{-# LANGUAGE TemplateHaskell #-}
module Drasil.Metadata (
    -- * Drasil Metadata
    watermark
) where

import Drasil.Metadata.Drasil (DrasilMeta(..), drasilMetaCfg)

-- | Drasil metadata. Don't export.
drasilMeta :: DrasilMeta
drasilMeta = $drasilMetaCfg

-- | Drasil's watermark for generated files.
watermark :: String
watermark = "Generated by Drasil " ++ version drasilMeta
