{-# LANGUAGE TemplateHaskell #-}
module Drasil.Metadata (
    -- * Drasil Metadata
    drasilMeta, watermark,
    -- * Domains
    module Drasil.Metadata.Domains,
    -- * Supported Software
    module Drasil.Metadata.SupportedSoftware
) where

import Drasil.Metadata.Domains
import Drasil.Metadata.Drasil (DrasilMeta(..), drasilMetaCfg)
import Drasil.Metadata.SupportedSoftware

-- | Drasil metadata.
drasilMeta :: DrasilMeta
drasilMeta = $drasilMetaCfg

-- | Drasil watermark for generated files.
watermark :: String
watermark = "Generated by Drasil " ++ version drasilMeta
