{-# LANGUAGE TemplateHaskell #-}
module Drasil.Metadata (
    -- * Drasil Metadata
    drasilMeta, watermark,
    -- * Domains
    module Drasil.Metadata.Domains,
    -- * Supported Software
    module Drasil.Metadata.SupportedSoftware,
    -- * Theory Concepts
    module Drasil.Metadata.TheoryConcepts
) where

import Drasil.Metadata.Domains
import Drasil.Metadata.Drasil (DrasilMeta(..), drasilMetaCfg)
import Drasil.Metadata.SupportedSoftware
import Drasil.Metadata.TheoryConcepts

-- | Drasil metadata.
drasilMeta :: DrasilMeta
drasilMeta = $drasilMetaCfg

-- | Drasil's watermark for generated files.
watermark :: String
watermark = "Generated by Drasil " ++ version drasilMeta
