{-#LANGUAGE TemplateHaskell#-}
module Data.Drasil.DrasilMetaCall (drasilMeta, DrasilMeta(..), watermark)where

import Data.Drasil.DrasilMeta (drasilMetaCfg, DrasilMeta(..))
import Data.Maybe (fromMaybe)


-- | Reads drasilMeta at compile-time
drasilMeta :: DrasilMeta
drasilMeta = $drasilMetaCfg

watermark :: String
watermark = "Generated by Drasil "
