name:        drasil
version:     0.2.0.0
author:      "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:  "Jacques Carette"
synopsis:	   A framework for code and document generation for scientific software.
github:      JacquesCarette/Drasil
homepage:    https://jacquescarette.github.io/Drasil/
description: Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- composition
- containers
- Decimal
- directory
- filepath
- lens
- mtl
- multiplate
- pretty
- split
- text
- time
- transformers
- unicode-names

ghc-options:
- -Wall
- -Wredundant-constraints

executables:
  codegenTest:
    main: Main
    source-dirs: drasil-code/test
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - drasil-code
    - drasil-gool
    when:
    - condition: false
      other-modules: Paths_drasil

  dblpendulum:
    main: Main
    source-dirs:
    - drasil-example/dblpendulum/app
    - drasil-example/dblpendulum/lib
    dependencies:
    - drasil-code
    - drasil-data
    - drasil-database
    - drasil-docLang
    - drasil-gen
    - drasil-gool
    - drasil-lang
    - drasil-metadata
    - drasil-printers
    - drasil-theory
    - drasil-utils
    when:
    - condition: false
      other-modules: Paths_drasil

internal-libraries:
  drasil-build:
    source-dirs: drasil-build/lib
    exposed-modules:
    - Build.Drasil
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-utils:
    source-dirs: drasil-utils/lib
    exposed-modules:
    - Utils.Drasil
    - Utils.Drasil.Document
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-gool:
    source-dirs: drasil-gool/lib
    dependencies:
    - drasil-utils
    exposed-modules:
    - GOOL.Drasil
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-lang:
    source-dirs: drasil-lang/lib
    dependencies:
    - drasil-utils
    exposed-modules:
    - Language.Drasil
    - Language.Drasil.Chunk.Concept.NamedCombinators
    - Language.Drasil.Development
    - Language.Drasil.Display
    - Language.Drasil.Expr.Development
    - Language.Drasil.Literal.Development
    - Language.Drasil.ModelExpr.Development
    - Language.Drasil.CodeExpr.Development
    - Language.Drasil.CodeExpr
    - Language.Drasil.NounPhrase.Combinators
    - Language.Drasil.Sentence.Combinators
    - Language.Drasil.ShortHands
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-metadata:
    source-dirs: drasil-metadata/lib
    dependencies:
    - drasil-lang
    exposed-modules:
    - Data.Drasil.Domains
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-theory:
    source-dirs: drasil-theory/lib
    dependencies:
    - drasil-lang
    - drasil-metadata
    - drasil-utils
    exposed-modules:
    - Theory.Drasil
    - Data.Drasil.TheoryConcepts
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-database:
    source-dirs: drasil-database/lib
    dependencies:
    - drasil-lang
    - drasil-theory
    - drasil-utils
    exposed-modules:
    - Database.Drasil
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-sysinfo:
    source-dirs: drasil-sysinfo/lib
    dependencies:
    - drasil-database
    - drasil-lang
    - drasil-theory
    exposed-modules:
    - SysInfo.Drasil
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-data:
    source-dirs: drasil-data/lib
    dependencies:
    - drasil-metadata
    - drasil-lang
    - drasil-theory
    - drasil-utils
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-printers:
    source-dirs: drasil-printers/lib
    dependencies:
    - drasil-database
    - drasil-lang
    - drasil-sysinfo
    - drasil-utils
    exposed-modules:
    - Language.Drasil.Printers
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-code:
    source-dirs: drasil-code/lib
    dependencies:
    - drasil-build
    - drasil-database
    - drasil-gool
    - drasil-lang
    - drasil-printers
    - drasil-sysinfo
    - drasil-theory
    - drasil-utils
    exposed-modules:
    - Language.Drasil.Code
    - Data.Drasil.ExternalLibraries.ODELibraries
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-docLang:
    source-dirs: drasil-docLang/lib
    dependencies:
    - drasil-lang
    - drasil-data
    - drasil-database
    - drasil-lang
    - drasil-printers
    - drasil-sysinfo
    - drasil-theory
    - drasil-utils 
    exposed-modules:
    - Drasil.DocLang
    - Drasil.DocLang.Notebook
    - Drasil.DocLang.SRS
    - Drasil.DocumentLanguage.Units
    - Drasil.DocumentLanguage.TraceabilityGraph
    - Drasil.SRSDocument
    when:
    - condition: false
      other-modules: Paths_drasil

  drasil-gen:
    source-dirs: drasil-gen/lib
    dependencies:
    - drasil-build
    - drasil-code
    - drasil-database
    - drasil-docLang
    - drasil-gool
    - drasil-lang
    - drasil-printers
    - drasil-sysinfo
    - drasil-utils
    exposed-modules:
    - Language.Drasil.Generate
    when:
    - condition: false
      other-modules: Paths_drasil
