resolver: lts-24.51

ghc-options:
  "$everything": -fwrite-ide-info -hiedir=.hie

packages:
- drasil-assets
- drasil-code
- drasil-data
- drasil-data-formats
- drasil-database
- drasil-srs
- drasil-example/bss
- drasil-example/dblpend
- drasil-example/gamephysics
- drasil-example/glassbr
- drasil-example/hghc
- drasil-example/pdcontroller
- drasil-example/projectile
- drasil-example/projectile-lesson
- drasil-example/sglpend
- drasil-example/ssp
- drasil-example/swhs
- drasil-example/swhsnopcm
- drasil-example/template
- drasil-file-handling
- drasil-gen
- drasil-gool
- drasil-lang
- drasil-lesson-plan
- drasil-makefile
- drasil-meta-analysis
- drasil-metadata
- drasil-printers
- drasil-system
- drasil-testing-kit
- drasil-theory
- drasil-utils
- drasil-website

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- multiplate-0.0.3@sha256:5d2ffc50d23c55008100b7a8b70f77b5fcce08c6f23822c5a6adc5b5b9356a32,1311
- unicode-names-3.2.0.0@sha256:fef7241d93170e26265e84553090253a5e8ee207645d47cf271816f5834d07d2,470
- unicode-properties-3.2.0.0@sha256:239766a6ac4322329353f6b9cd546024fd8c5f0235c8e32b3cba2d6bd245a699,1000
- transformers-0.6.1.1@sha256:80d128763c6965dfcddca2155b3dec3bb1970d476f0c8cceb4bb28608ab75e7c,3243

# Stan dependencies
- dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
- extensions-0.1.0.2@sha256:8de9ec6ebaa20fe9ccf78dd52c712de2a52f6ed9d33b5c3c6ce892f437acf412,5321
- trial-0.0.0.0@sha256:6fd1cf747fa2da4770f9ea6088f7beecdd302cdead6a70030bc027b814a95d50,4410
- trial-optparse-applicative-0.0.0.0@sha256:bf39583c25ff7b78ebe049b30ee7ec35714c7cfc2ee02d1e4e471c871668460d,2540
- trial-tomland-0.0.0.0@sha256:822774d645b22e24e3dca3a5b6776fe36a7505f267f87b01409c386b923d57c7,2541
- Cabal-syntax-3.12.1.0@sha256:6dbb06fb08ff77520947fb4c1ef281c9cea5b8dc7fd9a41ad62273fa916cf4b2,7407

# `make graphs` dependencies
- Cabal-3.12.1.0@sha256:08be296ddd941b3f9be4bd125fbb3e6857f5c707b8d10464f6f1d30c91ca3e5f,13551

# This configuration option allows the use of newer versions of dependencies than what is specified
allow-newer: true

# This configuration option specifies a list of dependencies for which newer versions are allowed.
# In this case, it's allowing newer versions of the 'stan' package.
allow-newer-deps:
- multiplate
- extensions

# Used only for a basic set of flags for haddock
build:
  haddock-deps: false

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

nix:
  pure: false

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
require-stack-version: ">=2.3.1"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

dump-logs: all

notify-if-no-run-tests: false
