package SWHSNoPCM;

/** \file Calculations.java
    \author Thulasi Jegatheesan
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

import java.util.ArrayList;
import org.apache.commons.math3.ode.FirstOrderIntegrator;
import org.apache.commons.math3.ode.nonstiff.DormandPrince54Integrator;

public class Calculations {
    
    /** \brief Calculates volume of water (m^3)
        \param V_tank volume of the cylindrical tank (m^3)
        \return volume of water (m^3)
    */
    public static double func_V_W(double V_tank) {
        return V_tank;
    }
    
    /** \brief Calculates mass of water (kg)
        \param rho_W density of water (kg/m^3)
        \param V_W volume of water (m^3)
        \return mass of water (kg)
    */
    public static double func_m_W(double rho_W, double V_W) {
        return V_W * rho_W;
    }
    
    /** \brief Calculates ODE parameter for water related to decay time (s)
        \param C_W specific heat capacity of water (J/(kg degreeC))
        \param h_C convective heat transfer coefficient between coil and water (W/(m^2 degreeC))
        \param A_C heating coil surface area (m^2)
        \param m_W mass of water (kg)
        \return ODE parameter for water related to decay time (s)
    */
    public static double func_tau_W(double C_W, double h_C, double A_C, double m_W) {
        return m_W * C_W / (h_C * A_C);
    }
    
    /** \brief Calculates temperature of the water (degreeC)
        \param T_C temperature of the heating coil (degreeC)
        \param T_init initial temperature (degreeC)
        \param t_final final time (s)
        \param A_tol absolute tolerance
        \param R_tol relative tolerance
        \param t_step time step for simulation (s)
        \param tau_W ODE parameter for water related to decay time (s)
        \return temperature of the water (degreeC)
    */
    public static ArrayList<Double> func_T_W(double T_C, double T_init, double t_final, double A_tol, double R_tol, double t_step, double tau_W) {
        ArrayList<Double> T_W;
        ODEStepHandler stepHandler = new ODEStepHandler();
        ODE ode = new ODE(tau_W, T_C);
        double[] curr_vals = {T_init};
        
        FirstOrderIntegrator it = new DormandPrince54Integrator(t_step, t_step, A_tol, R_tol);
        it.addStepHandler(stepHandler);
        it.integrate(ode, 0.0, curr_vals, t_final, curr_vals);
        T_W = stepHandler.T_W;
        
        return T_W;
    }
}
