package SWHSNoPCM;

/** \file Constants.java
    \author Thulasi Jegatheesan
    \brief Provides the structure for holding constant values
    \note Generated by Drasil v0.1-alpha
*/

/** \brief Structure for holding the constant values
*/
public class Constants {
    public static final double pi = 3.14159265;
    public static final double L_min = 0.1;
    public static final double L_max = 50.0;
    public static final double rho_Wmin = 950.0;
    public static final double rho_Wmax = 1000.0;
    public static final double A_Cmax = 100000.0;
    public static final double C_Wmin = 4170.0;
    public static final double C_Wmax = 4210.0;
    public static final double h_Cmin = 10.0;
    public static final double h_Cmax = 10000.0;
    public static final double t_finalmax = 86400.0;
    public static final double AR_min = 1.0e-2;
    public static final double AR_max = 100.0;
    
}
