[book]
language = "en"
multilingual = false
src = "src"
title = "Software Requirements Specification for Solar Water Heating Systems Incorporating PCM"
[output.html]
smart-punctuation = true
mathjax-support = true
