name:                drasil-codeLang
version:             0.1.0.0
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith, Harmanpreet Singh Sagar"
maintainer:          "Jacques Carette"
synopsis:	     A framework for code and document generation for scientific software - Code Language SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - CodeLang.Drasil
  when:
  - condition: false
    other-modules: Paths_drasil_codeLang
