## \file Calculations.py
# \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
# \brief Provides functions for calculating the outputs
# \note Generated by Drasil v0.1-alpha

import math

## \brief Calculates flight duration (s)
# \param inParams structure holding the input values
# \param g magnitude of gravitational acceleration (m/s^2)
# \return flight duration (s)
def func_t_flight(inParams, g):
    return 2.0 * inParams.v_launch * math.sin(inParams.theta) / g

## \brief Calculates landing position (m)
# \param inParams structure holding the input values
# \param g magnitude of gravitational acceleration (m/s^2)
# \return landing position (m)
def func_p_land(inParams, g):
    return 2.0 * inParams.v_launch ** 2.0 * math.sin(inParams.theta) * math.cos(inParams.theta) / g

## \brief Calculates distance between the target position and the landing position (m)
# \param inParams structure holding the input values
# \param p_land landing position (m)
# \return distance between the target position and the landing position (m)
def func_d_offset(inParams, p_land):
    return p_land - inParams.p_target
