## \file OutputFormat.py
# \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
# \brief Provides the function for writing outputs
# \note Generated by Drasil v0.1-alpha

## \brief Writes the output values to output.txt
# \param d_offset distance between the target position and the landing position (m)
# \param t_flight flight duration (s)
def write_output(d_offset, t_flight):
    outputfile = open("output.txt", "w")
    print("d_offset = ", end="", file=outputfile)
    print(d_offset, file=outputfile)
    print("t_flight = ", end="", file=outputfile)
    print(t_flight, file=outputfile)
    outputfile.close()
