name:                drasil-printing
version:             0.1.0.0
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:            A framework for code and document generation for scientific software - Printing Infrastructure SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

language: Haskell2010
default-extensions:
- StrictData

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- lens
- pretty
- containers
- MissingH
- filepath
- directory
- drasil-database
- drasil-lang
- drasil-metadata
- drasil-theory
- drasil-utils
- split

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - Language.Drasil.Config
  - Language.Drasil.Plain.Print
  - Language.Drasil.Printing.AST
  - Language.Drasil.Printing.Citation
  - Language.Drasil.Printing.Helpers
  - Language.Drasil.Printing.Import
  - Language.Drasil.Printing.LayoutObj
  - Language.Drasil.Printing.PrintingInformation
  other-modules:
  - Language.Drasil.Printing.Import.CodeExpr
  - Language.Drasil.Printing.Import.Document
  - Language.Drasil.Printing.Import.Expr
  - Language.Drasil.Printing.Import.Helpers
  - Language.Drasil.Printing.Import.Literal
  - Language.Drasil.Printing.Import.ModelExpr
  - Language.Drasil.Printing.Import.Sentence
  - Language.Drasil.Printing.Import.Space
  - Language.Drasil.Printing.Import.Symbol
  when:
  - condition: false
    other-modules: Paths_drasil_printing
