/** \file Constants.cs
    \author Naveen Ganesh Muralidharan
    \brief Provides the structure for holding constant values
    \Generated by Drasil v0.1-alpha
*/
/** \brief Structure for holding the constant values
*/
public class Constants {
    public const double AbsTol = 1.0e-10;
    public const double RelTol = 1.0e-10;
    
}
