""" Projectile.jl
    A program to predict whether a launched projectile hits its target.
    - Authors: Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    - Note: Generated by Drasil v0.1-alpha
"""

module Projectile

""" Calculates flight duration (s)
    - Parameter v_launch: launch speed (m/s)
    - Parameter theta: launch angle (rad)
    - Parameter g: magnitude of gravitational acceleration (m/s^2)
    - Returns: flight duration (s)
"""
function func_t_flight(v_launch::Float64, theta::Float64, g::Float64)
    return 2.0 * v_launch * sin(theta) / g
end

""" Calculates landing position (m)
    - Parameter v_launch: launch speed (m/s)
    - Parameter theta: launch angle (rad)
    - Parameter g: magnitude of gravitational acceleration (m/s^2)
    - Returns: landing position (m)
"""
function func_p_land(v_launch::Float64, theta::Float64, g::Float64)
    return 2.0 * v_launch ^ 2.0 * sin(theta) * cos(theta) / g
end

""" Calculates distance between the target position and the landing position (m)
    - Parameter p_target: target position (m)
    - Parameter p_land: landing position (m)
    - Returns: distance between the target position and the landing position (m)
"""
function func_d_offset(p_target::Float64, p_land::Float64)
    return p_land - p_target
end

""" Reads input from a file with the given file name
    - Parameter filename: name of the input file
    - Returns: launch speed (m/s)
    - Returns: launch angle (rad)
    - Returns: target position (m)
"""
function get_input(filename::String)
    infile = open(filename, "r")
    readline(infile)
    v_launch = parse(Float64, readline(infile))
    readline(infile)
    theta = parse(Float64, readline(infile))
    readline(infile)
    p_target = parse(Float64, readline(infile))
    close(infile)
    
    return v_launch, theta, p_target
end

""" Verifies that input values satisfy the physical constraints
    - Parameter v_launch: launch speed (m/s)
    - Parameter theta: launch angle (rad)
    - Parameter p_target: target position (m)
"""
function input_constraints(v_launch::Float64, theta::Float64, p_target::Float64)
    if !(v_launch > 0.0)
        print("Warning: ")
        print("v_launch has value ")
        print(v_launch)
        print(", but is suggested to be ")
        print("above ")
        print(0.0)
        println(".")
    end
    if !(0.0 < theta && theta < pi / 2.0)
        print("Warning: ")
        print("theta has value ")
        print(theta)
        print(", but is suggested to be ")
        print("between ")
        print(0.0)
        print(" and ")
        print(pi / 2.0)
        print(" ((pi)/(2))")
        println(".")
    end
    if !(p_target > 0.0)
        print("Warning: ")
        print("p_target has value ")
        print(p_target)
        print(", but is suggested to be ")
        print("above ")
        print(0.0)
        println(".")
    end
end

""" Writes the output values to output.txt
    - Parameter d_offset: distance between the target position and the landing position (m)
    - Parameter t_flight: flight duration (s)
"""
function write_output(d_offset::Float64, t_flight::Float64)
    outputfile = open("output.txt", "w")
    print(outputfile, "d_offset = ")
    println(outputfile, d_offset)
    print(outputfile, "t_flight = ")
    println(outputfile, t_flight)
    close(outputfile)
end

global filename = ARGS[1]
global g = 9.8
global epsilon = 2.0e-2
v_launch, theta, p_target = get_input(filename)
input_constraints(v_launch, theta, p_target)
global t_flight = func_t_flight(v_launch, theta, g)
global p_land = func_p_land(v_launch, theta, g)
global d_offset = func_d_offset(p_target, p_land)
write_output(d_offset, t_flight)

end
