## \file OOTest.py
# \author Brandon Bosman
# \date Apr. 24, 2026
# \brief Tests various aspects of general object functionality
# \note Generated by Drasil v0.1-alpha

## \brief Basic class to test some stuff
class testClass:
    y = 17.4
    
    def __init__(self, x):
        self.x = x
    
    def mulByX(self, num):
        return self.x * num
    
    def square(self, num):
        return num * num

print(testClass.y)
testObj = testClass(56)
print(testObj.mulByX(42))
print(testClass.square(2.5))
