/** \file InputParameters.hpp
    \author Xinlu Yan
    \brief Provides the function for reading inputs and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

#ifndef InputParameters_h
#define InputParameters_h

#include <string>

#include "Constants.hpp"

using std::ifstream;
using std::string;

/** \brief Reads input from a file with the given file name
    \param filename name of the input file
    \param m_1 mass of the first star (kg)
    \param m_2 mass of the second star (kg)
    \param x_1_0 initial x-position of the first star (m)
    \param y_1_0 initial y-position of the first star (m)
    \param x_2_0 initial x-position of the second star (m)
    \param y_2_0 initial y-position of the second star (m)
    \param v_x1_0 initial x-velocity of the first star (m/s)
    \param v_y1_0 initial y-velocity of the first star (m/s)
    \param v_x2_0 initial x-velocity of the second star (m/s)
    \param v_y2_0 initial y-velocity of the second star (m/s)
    \param t_final final time (s)
*/
void get_input(string filename, double &m_1, double &m_2, double &x_1_0, double &y_1_0, double &x_2_0, double &y_2_0, double &v_x1_0, double &v_y1_0, double &v_x2_0, double &v_y2_0, double &t_final);

/** \brief Verifies that input values satisfy the physical constraints and software constraints
    \param m_1 mass of the first star (kg)
    \param m_2 mass of the second star (kg)
    \param x_1_0 initial x-position of the first star (m)
    \param y_1_0 initial y-position of the first star (m)
    \param x_2_0 initial x-position of the second star (m)
    \param y_2_0 initial y-position of the second star (m)
    \param v_x1_0 initial x-velocity of the first star (m/s)
    \param v_y1_0 initial y-velocity of the first star (m/s)
    \param v_x2_0 initial x-velocity of the second star (m/s)
    \param v_y2_0 initial y-velocity of the second star (m/s)
    \param t_final final time (s)
*/
void input_constraints(double m_1, double m_2, double x_1_0, double y_1_0, double x_2_0, double y_2_0, double v_x1_0, double v_y1_0, double v_x2_0, double v_y2_0, double t_final);

#endif
