## \file OutputFormat.py
# \author Xinlu Yan
# \brief Provides the function for writing outputs
# \note Generated by Drasil v0.1-alpha

## \brief Writes the output values to output.txt
# \param q dependent variables (m)
def write_output(q):
    outputfile = open("output.txt", "w")
    print("q = ", end="", file=outputfile)
    print("[", end="", file=outputfile)
    for list_i1 in range(0, len(q), 1):
        print("[", end="", file=outputfile)
        for list_i2 in range(0, len(q[list_i1]), 1):
            print(q[list_i1][list_i2], end="", file=outputfile)
            if list_i2 < len(q[list_i1]) - 1:
                print(", ", end="", file=outputfile)
        print("]", end="", file=outputfile)
        if list_i1 < len(q) - 1:
            print(", ", end="", file=outputfile)
    print("]", file=outputfile)
    outputfile.close()
