/** \file OutputFormat.cs
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.IO;

public class OutputFormat {
    
    /** \brief Writes the output values to output.txt
        \param d_offset distance between the target position and the landing position (m)
        \param t_flight flight duration (s)
    */
    public static void write_output(double d_offset, double t_flight) {
        StreamWriter outputfile;
        outputfile = new StreamWriter("output.txt", false);
        outputfile.Write("d_offset = ");
        outputfile.WriteLine(d_offset);
        outputfile.Write("t_flight = ");
        outputfile.WriteLine(t_flight);
        outputfile.Close();
    }
}
