## \file OutputFormat.py
# \author Olu Owojaiye
# \brief Provides the function for writing outputs
# \note Generated by Drasil v0.1-alpha

## \brief Writes the output values to output.txt
# \param θ_p displacement angle of the pendulum (rad)
def write_output(θ_p):
    outputfile = open("output.txt", "w")
    print("θ_p = ", end="", file=outputfile)
    print(θ_p, file=outputfile)
    outputfile.close()
