/** main.swift
    Controls the flow of the program
    - Authors: Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    - Note: Generated by Drasil v0.1-alpha
*/

var filename: String = CommandLine.arguments[0]
var g: Float = 9.8
var epsilon: Float = 2.0e-2
var v_launch: Float
var theta: Float
var p_target: Float
(v_launch, theta, p_target) = try get_input(filename)
input_constraints(v_launch, theta, p_target)
var t_flight: Float = func_t_flight(v_launch, theta, g)
var p_land: Float = func_p_land(v_launch, theta, g)
var d_offset: Float = func_d_offset(p_target, p_land)
var s: String = func_s(p_target, epsilon, d_offset)
try write_output(s, d_offset, t_flight)
