## \file Control.py
# \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
# \brief Controls the flow of the program
# \note Generated by Drasil v0.1-alpha

import sys

import Calculations
import InputParameters
import OutputFormat

filename = sys.argv[1]
g = 9.8
epsilon = 2.0e-2
v_launch, theta, p_target = InputParameters.get_input(filename)
InputParameters.input_constraints(v_launch, theta, p_target)
t_flight = Calculations.func_t_flight(v_launch, theta, g)
p_land = Calculations.func_p_land(v_launch, theta, g)
d_offset = Calculations.func_d_offset(p_target, p_land)
s = Calculations.func_s(p_target, epsilon, d_offset)
OutputFormat.write_output(s, d_offset, t_flight)
