name:                drasil-code
version:             0.1.9.0
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:	     A framework for code and document generation for scientific software - Code SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- lens
- containers
- pretty
- mtl
- directory
- filepath
- split
- drasil-build
- drasil-database
- drasil-gool
- drasil-lang
- drasil-printers
- drasil-sysinfo
- drasil-theory
- drasil-utils

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - Language.Drasil.Code
  - Data.Drasil.ExternalLibraries.ODELibraries
  other-modules:
    - Language.Drasil.Chunk.Code
    - Language.Drasil.Chunk.CodeBase
    - Language.Drasil.Chunk.CodeDefinition
    - Language.Drasil.Chunk.ConstraintMap
    - Language.Drasil.Chunk.NamedArgument
    - Language.Drasil.Chunk.Parameter
    - Language.Drasil.Code.Code
    - Language.Drasil.Code.CodeQuantityDicts
    - Language.Drasil.Code.DataDesc
    - Language.Drasil.Code.ExternalLibrary
    - Language.Drasil.Code.ExternalLibraryCall
    - Language.Drasil.Code.ExtLibImport
    - Language.Drasil.Code.Lang
    - Language.Drasil.Code.Imperative.Build.AST
    - Language.Drasil.Code.Imperative.Build.Import
    - Language.Drasil.Code.Imperative.ConceptMatch
    - Language.Drasil.Code.Imperative.SpaceMatch
    - Language.Drasil.Code.Imperative.Doxygen.Import
    - Language.Drasil.Code.Imperative.ReadInput
    - Language.Drasil.Code.Imperative.WriteInput
    - Language.Drasil.Code.Imperative.WriteReadMe
    - Language.Drasil.Code.Imperative.GOOL.Data
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.LanguagePolymorphic
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.JavaRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.PythonRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.CSharpRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.CppRenderer
    - Language.Drasil.Code.Imperative.GOOL.LanguageRenderer.SwiftRenderer
    - Language.Drasil.Code.Imperative.GOOL.ClassInterface
    - Language.Drasil.Code.Imperative.Comments
    - Language.Drasil.Code.Imperative.Descriptions
    - Language.Drasil.Code.Imperative.FunctionCalls
    - Language.Drasil.Code.Imperative.GenerateGOOL
    - Language.Drasil.Code.Imperative.Generator
    - Language.Drasil.Code.Imperative.GenODE
    - Language.Drasil.Code.Imperative.Helpers
    - Language.Drasil.Code.Imperative.Import
    - Language.Drasil.Code.Imperative.Logging
    - Language.Drasil.Code.Imperative.Modules
    - Language.Drasil.Code.Imperative.Parameters
    - Language.Drasil.Code.Imperative.DrasilState
    - Language.Drasil.Code.CodeGeneration
    - Language.Drasil.Data.ODEInfo
    - Language.Drasil.Data.ODELibPckg
    - Language.Drasil.Choices
    - Language.Drasil.CodeSpec
    - Language.Drasil.Mod
  when:
  - condition: false
    other-modules: Paths_drasil_code

executables:
  codegenTest:
    main: Main
    source-dirs: test
    other-modules:
    - FileTests
    - HelloWorld
    - Helper
    - Observer
    - PatternTest
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - drasil-code
