name:                drasil-code
version:             0.1.9.0
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:	     A framework for code and document generation for scientific software - Code SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

language: Haskell2010
default-extensions:
- StrictData

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- lens
- containers
- pretty
- mtl
- directory
- filepath
- split
- drasil-build
- drasil-database
- drasil-gool
- drasil-lang
- drasil-metadata
- drasil-printers
- drasil-system
- drasil-theory
- drasil-utils
- deriving-compat

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - Language.Drasil.Code
  - Language.Drasil.GOOL
  - Data.Drasil.ExternalLibraries.ODELibraries
  when:
  - condition: false
    other-modules: Paths_drasil_code

executables:
  codegenTest:
    main: Main
    source-dirs: test
    other-modules:
    - FileTests
    - HelloWorld
    - Helper
    - GOOL.Observer
    - GOOL.PatternTest
    - VectorTest
    - NameGenTest
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - drasil-code
