# Project Name and Purpose: Projectile - To predict whether a launched projectile hits its target.

build:

doc: doxConfig InputFormat.py InputConstraints.py Calculations.py OutputFormat.py
	doxygen doxConfig

.PHONY: build doc
