resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/20.yaml

packages:
- .
- ../drasil-build
- ../drasil-code
- ../drasil-data
- ../drasil-database
- ../drasil-docLang
- ../drasil-gen
- ../drasil-gool
- ../drasil-lang
- ../drasil-metadata
- ../drasil-printers
- ../drasil-sysinfo
- ../drasil-theory
- ../drasil-utils
- ../drasil-example/sglpendulum
- ../drasil-example/dblpendulum
- ../drasil-example/gamephysics
- ../drasil-example/glassbr
- ../drasil-example/hghc
- ../drasil-example/nopcm
- ../drasil-example/pdcontroller
- ../drasil-example/projectile
- ../drasil-example/ssp
- ../drasil-example/swhs
- ../drasil-example/template

extra-deps:
- unicode-names-3.2.0.0@sha256:fef7241d93170e26265e84553090253a5e8ee207645d47cf271816f5834d07d2,470
- unicode-properties-3.2.0.0@sha256:239766a6ac4322329353f6b9cd546024fd8c5f0235c8e32b3cba2d6bd245a699,1000
- multiplate-0.0.3@sha256:5d2ffc50d23c55008100b7a8b70f77b5fcce08c6f23822c5a6adc5b5b9356a32,1311
