spec-version: 0.36.0
name:         drasil-file-handling
version:      0.1.1.0
author:       "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:   "Jacques Carette"
synopsis:     A framework for code and document generation for scientific software - file-handling SubPackage
github:       JacquesCarette/Drasil
homepage:     https://jacquescarette.github.io/Drasil/
description:  Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

language: Haskell2010
default-extensions:
- DeriveFunctor
- ImportQualifiedPost
- StrictData

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- pretty
- prettyprinter
- template-haskell
- file-io >= 0.1.6
- os-string
- process
- tasty
- text
- bytestring

ghc-options:
- -Wall
- -Wredundant-constraints
- -Wmissing-export-lists
- -threaded

library:
  source-dirs: lib
  exposed-modules:
  - Drasil.FileHandling
  - Drasil.FileHandling.Legacy

tests:
  drasil-file-handling-test:
    source-dirs: test
    main: Main.hs
    dependencies:
    - drasil-file-handling
    - hedgehog
    - tasty
    - tasty-hedgehog
    - tasty-hunit
