/** \file Calculations.hpp
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef Calculations_h
#define Calculations_h

#include "InputParameters.hpp"

/** \brief Calculates flight duration (s)
    \param inParams structure holding the input values
    \param g magnitude of gravitational acceleration (m/s^2)
    \return flight duration (s)
*/
double func_t_flight(InputParameters &inParams, double g);

/** \brief Calculates landing position (m)
    \param inParams structure holding the input values
    \param g magnitude of gravitational acceleration (m/s^2)
    \return landing position (m)
*/
double func_p_land(InputParameters &inParams, double g);

/** \brief Calculates distance between the target position and the landing position (m)
    \param inParams structure holding the input values
    \param p_land landing position (m)
    \return distance between the target position and the landing position (m)
*/
double func_d_offset(InputParameters &inParams, double p_land);

#endif
