/** \file OutputFormat.hpp
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef OutputFormat_h
#define OutputFormat_h

#include <string>

using std::ofstream;
using std::string;

/** \brief Writes the output values to output.txt
    \param d_offset distance between the target position and the landing position (m)
    \param t_flight flight duration (s)
*/
void write_output(double d_offset, double t_flight);

#endif
