% HelloWorld.m
% Tests various GProc functions. It should run without errors.
% - Authors: Brooks MacLachlan, Brandon Bosman, and Xinlu Yan
% - Note: Generated by Drasil v0.1-alpha

function HelloWorld(varargin)
    % Initializing variables
    b = 5;
    arr = [1, 2, 3];
    fprintf('%s', "Value of arr: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(arr) - 1
        fprintf('%g', arr(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(arr) > 0
        fprintf('%g', arr(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "Length of arr: ");
    fprintf('%g\n', length(arr));
    arr2(1) = 4;
    arr2(2) = 5;
    arr2(3) = 6;
    fprintf('%s', "Value of arr2: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(arr2) - 1
        fprintf('%g', arr2(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(arr2) > 0
        fprintf('%g', arr2(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "Length of arr2: ");
    fprintf('%g\n', length(arr2));
    myOtherList = [1.0, 1.5];
    arr_copy = arr;
    fprintf('%s', "Value of arr_copy: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(arr_copy) - 1
        fprintf('%g', arr_copy(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(arr_copy) > 0
        fprintf('%g', arr_copy(end));
    end
    fprintf('%s\n', "]");
    arr(2) = 42;
    fprintf('%s', "Value of arr after modifying arr: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(arr) - 1
        fprintf('%g', arr(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(arr) > 0
        fprintf('%g', arr(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "Value of arr_copy after modifying arr: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(arr_copy) - 1
        fprintf('%g', arr_copy(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(arr_copy) > 0
        fprintf('%g', arr_copy(end));
    end
    fprintf('%s\n', "]");
    oneIndex = find(myOtherList == 1.0, 1) - 1;
    fprintf('%g\n', oneIndex);
    a = length(myOtherList);
    assert(a == 2, "List size should be 2");
    myOtherList = [myOtherList(1:(3 - 1)), 2.0, myOtherList(3:end)];
    myOtherList(length(myOtherList) + 1) = 2.5;
    e = myOtherList(2);
    myOtherList(2) = 17.4;
    myName = {};
    myName = strsplit("Brooks Mac", " ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(myName) - 1
        fprintf('%s', myName{list_i1 + 1});
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(myName) > 0
        fprintf('%s', myName{end});
    end
    fprintf('%s\n', "]");
    boringList = [false, false, false, false, false];
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(boringList) - 1
        fprintf('%g', boringList(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(boringList) > 0
        fprintf('%g', boringList(end));
    end
    fprintf('%s\n', "]");
    assert(b == 5, "b should be 5");
    assert(length(myOtherList) == 4, "myOtherList should have 4 elements");
    assert(oneIndex == 0, "oneIndex should be 0");
    s = [4, 7, 5];
    assert(ismember(7, s), "Set s should contain 7");
    
    % List slicing tests
    % Create variables for list slices
    mySlicedList = [];
    mySlicedList2 = [];
    mySlicedList3 = [];
    mySlicedList4 = [];
    mySlicedList5 = [];
    mySlicedList6 = [];
    mySlicedList7 = [];
    mySlicedList8 = [];
    mySlicedList9 = [];
    mySlicedList10 = [];
    mySlicedList11 = [];
    
    % Create some variables for later tests
    x = 3;
    y = 1;
    z = -1;
    
    temp = [];
    i = 1;
    while i < 3
        temp(length(temp) + 1) = myOtherList(i + 1);
        i = i + 1;
    end
    mySlicedList = temp;
    
    temp0 = [];
    j = 1;
    while j < 4
        temp0(length(temp0) + 1) = myOtherList(j + 1);
        j = j + 2;
    end
    mySlicedList2 = temp0;
    
    temp1 = [];
    k = 1;
    while k < length(myOtherList)
        temp1(length(temp1) + 1) = myOtherList(k + 1);
        k = k + 1;
    end
    mySlicedList3 = temp1;
    
    temp2 = [];
    i0 = 3;
    while i0 < 1
        temp2(length(temp2) + 1) = myOtherList(i0 + 1);
        i0 = i0 + 1;
    end
    mySlicedList4 = temp2;
    
    temp3 = [];
    i1 = 3;
    while i1 > 1
        temp3(length(temp3) + 1) = myOtherList(i1 + 1);
        i1 = i1 - 1;
    end
    mySlicedList5 = temp3;
    
    temp4 = [];
    i2 = length(myOtherList) - 1;
    while i2 > 1
        temp4(length(temp4) + 1) = myOtherList(i2 + 1);
        i2 = i2 - 1;
    end
    mySlicedList6 = temp4;
    
    temp5 = [];
    i3 = 3;
    while i3 > -1
        temp5(length(temp5) + 1) = myOtherList(i3 + 1);
        i3 = i3 - 1;
    end
    mySlicedList7 = temp5;
    
    temp6 = [];
    i4 = 3;
    while 0 < i4 && i4 <= 3 && z < 0
        temp6(length(temp6) + 1) = myOtherList(i4 + 1);
        i4 = i4 + z;
    end
    mySlicedList8 = temp6;
    
    temp7 = [];
    i5 = x;
    while x <= i5 && i5 < y && z > 0 || y < i5 && i5 <= x && z < 0
        temp7(length(temp7) + 1) = myOtherList(i5 + 1);
        i5 = i5 + z;
    end
    mySlicedList9 = temp7;
    
    temp8 = [];
    endIdx = ((z > 0) .* (length(myOtherList)) + ~(z > 0) .* (-1));
    i6 = 2;
    while 2 <= i6 && i6 < endIdx + 1 && z > 0 || endIdx + 1 < i6 && i6 <= 2 && z < 0
        temp8(length(temp8) + 1) = myOtherList(i6 + 1);
        i6 = i6 + z;
    end
    mySlicedList10 = temp8;
    
    temp9 = [];
    endIdx0 = ((z > 0) .* (length(myOtherList)) + ~(z > 0) .* (-1));
    i7 = 2;
    while 2 <= i7 && i7 < endIdx0 + 1 && z > 0 || endIdx0 + 1 < i7 && i7 <= 2 && z < 0
        temp9(length(temp9) + 1) = myOtherList(i7 + 1);
        i7 = i7 + z;
    end
    mySlicedList10 = temp9;
    
    temp10 = [];
    i8 = y;
    while y <= i8 && i8 < x && z > 0 || x < i8 && i8 <= y && z < 0
        temp10(length(temp10) + 1) = myOtherList(i8 + 1);
        i8 = i8 + z;
    end
    mySlicedList11 = temp10;
    
    % Print results of list slicing tests
    fprintf('%s\n', "");
    fprintf('%s\n', "List slicing:");
    fprintf('%s', "myOtherList: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(myOtherList) - 1
        fprintf('%g', myOtherList(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(myOtherList) > 0
        fprintf('%g', myOtherList(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList) - 1
        fprintf('%g', mySlicedList(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList) > 0
        fprintf('%g', mySlicedList(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList2: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList2) - 1
        fprintf('%g', mySlicedList2(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList2) > 0
        fprintf('%g', mySlicedList2(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList3: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList3) - 1
        fprintf('%g', mySlicedList3(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList3) > 0
        fprintf('%g', mySlicedList3(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList4: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList4) - 1
        fprintf('%g', mySlicedList4(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList4) > 0
        fprintf('%g', mySlicedList4(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList5: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList5) - 1
        fprintf('%g', mySlicedList5(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList5) > 0
        fprintf('%g', mySlicedList5(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList6: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList6) - 1
        fprintf('%g', mySlicedList6(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList6) > 0
        fprintf('%g', mySlicedList6(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList7: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList7) - 1
        fprintf('%g', mySlicedList7(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList7) > 0
        fprintf('%g', mySlicedList7(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList8: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList8) - 1
        fprintf('%g', mySlicedList8(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList8) > 0
        fprintf('%g', mySlicedList8(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList9: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList9) - 1
        fprintf('%g', mySlicedList9(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList9) > 0
        fprintf('%g', mySlicedList9(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList10: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList10) - 1
        fprintf('%g', mySlicedList10(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList10) > 0
        fprintf('%g', mySlicedList10(end));
    end
    fprintf('%s\n', "]");
    fprintf('%s', "mySlicedList11: ");
    fprintf('%s', "[");
    list_i1 = 0;
    while list_i1 < length(mySlicedList11) - 1
        fprintf('%g', mySlicedList11(list_i1 + 1));
        fprintf('%s', ", ");
        list_i1 = list_i1 + 1;
    end
    if length(mySlicedList11) > 0
        fprintf('%g', mySlicedList11(end));
    end
    fprintf('%s\n', "]");
    
    fprintf('%s\n', "");
    if b >= 6
        dummy = "dummy";
    elseif b == 5
        % If body -----------------------------------------------------------------
        a = 5;
        b = a + 2;
        c = b + 3;
        d = b;
        d = d - a;
        c = c - d;
        b = b + 17;
        c = c + 17;
        a = a + 1;
        d = d + 1;
        c = c - 1;
        b = b - 1;
        myList = [];
        myConst = "Imconstant";
        fprintf('%s\n', myConst);
        fprintf('%g\n', a);
        fprintf('%g\n', b);
        fprintf('%g\n', c);
        fprintf('%g\n', d);
        fprintf('%s', "[");
        list_i1 = 0;
        while list_i1 < length(myOtherList) - 1
            fprintf('%g', myOtherList(list_i1 + 1));
            fprintf('%s', ", ");
            list_i1 = list_i1 + 1;
        end
        if length(myOtherList) > 0
            fprintf('%g', myOtherList(end));
        end
        fprintf('%s\n', "]");
        fprintf('%s', "[");
        list_i1 = 0;
        while list_i1 < length(mySlicedList) - 1
            fprintf('%g', mySlicedList(list_i1 + 1));
            fprintf('%s', ", ");
            list_i1 = list_i1 + 1;
        end
        if length(mySlicedList) > 0
            fprintf('%g', mySlicedList(end));
        end
        fprintf('%s\n', "]");
        fprintf('%s\n', "Type an int");
        d = str2double(input("", "s"));
        fprintf('%s\n', "Type another");
        input("", "s");
        
        fprintf('%s\n', " too");
        fprintf('%s', "boo");
        fprintf('%g', true);
        fprintf('%g', 0);
        fprintf('%c', 'c');
        fprintf('%g\n', ~(true));
        fprintf('%g\n', -1);
        fprintf('%g\n', sqrt(4.0));
        fprintf('%g\n', abs(-4));
        fprintf('%g\n', log10(2.0));
        fprintf('%g\n', log(2.0));
        fprintf('%g\n', exp(-2.0));
        fprintf('%g\n', sin(2.0));
        fprintf('%g\n', cos(2.0));
        fprintf('%g\n', tan(2.0));
        fprintf('%g\n', tan(2.0));
        fprintf('%g\n', true && false);
        fprintf('%g\n', true || false);
        fprintf('%g\n', true && ~(false));
        fprintf('%g\n', ~(true && true));
        fprintf('%g\n', 6 + 2);
        fprintf('%g\n', 6 - 2);
        fprintf('%g\n', 6 * 2);
        fprintf('%g\n', 6 / 2);
        fprintf('%g\n', mod(6, 4));
        fprintf('%g\n', 6 ^ 2);
        fprintf('%g\n', 6 + 2 * 3);
        fprintf('%g\n', 1.0 / sin(1.0));
        fprintf('%g\n', 1.0 / cos(1.0));
        fprintf('%g\n', a);
        fprintf('%g\n', ((true) .* (5) + ~(true) .* (0)));
        fprintf('%g\n', 1.0 / tan(1.0));
        % End If body -------------------------------------------------------------
    else
        fprintf('%s\n', varargin{6});
    end
    if ~(isempty(boringList))
        fprintf('%s\n', "Ew, boring list!");
    else
        fprintf('%s\n', "Great, no bores!");
    end
    if a == 5
        b = 10;
    elseif a == 0
        b = 5;
    else
        b = 0;
    end
    for i = 0:1:9
        fprintf('%g\n', i);
    end
    while a < 13
        fprintf('%s\n', "Hello");
        a = a + 1;
    end
    for num = myOtherList
        fprintf('%g\n', doubleAndAdd(num, 1.0));
    end
    try error("Good-bye!");
    catch e
        fprintf('%s\n', "Caught intentional error");
    end
end
