/** \file HelloWorld.cs
    \author Brandon Bosman
    \brief Advent of Code Day 1
    \note Generated by Drasil v0.1-alpha
*/

using System;
using System.Collections.Generic;
using System.IO;

public class HelloWorld {
    
    public static void Main(string[] args) {
        // Get input
        string filePath = "../../../../drasil-code/test/input.txt";
        StreamReader fileHandle;
        List<string> fileContents;
        fileHandle = new StreamReader(filePath);
        while (!(fileHandle.EndOfStream)) {
            fileContents.Add(fileHandle.ReadLine());
        }
        fileHandle.Close();
        
        // Process input
        List<int> list1 = new int[] {};
        List<int> list2 = new int[] {};
        foreach (string line in fileContents) {
            List<string> splitLine;
            splitLine = new List<string>(line.Split(' '));
            list1.Add(strToInt(splitLine[0]));
            list2.Add(strToInt(splitLine[3]));
        }
        selectionSort(list1);
        selectionSort(list2);
        
        // Calculate distance and print out
        int distance = 0;
        for (int i = 0; i < list1.Count; i += 1) {
            int partDistance = list1[i] - list2[i];
            if (partDistance < 0) {
                partDistance = -partDistance;
            }
            distance += partDistance;
        }
        Console.Write("Distance: ");
        Console.WriteLine(distance);
    }
    
    /** \brief Converts a string to integer
        \param str String to be converted
        \return Integer value of the string
    */
    public static int strToInt(List<char> str) {
        int val = 0;
        for (int i = 0; i < str.Count; i += 1) {
            int digit;
            switch(str[i]) {
                case '0':
                    digit = 0;
                    break;
                case '1':
                    digit = 1;
                    break;
                case '2':
                    digit = 2;
                    break;
                case '3':
                    digit = 3;
                    break;
                case '4':
                    digit = 4;
                    break;
                case '5':
                    digit = 5;
                    break;
                case '6':
                    digit = 6;
                    break;
                case '7':
                    digit = 7;
                    break;
                case '8':
                    digit = 8;
                    break;
                case '9':
                    digit = 9;
                    break;
                case ' ':
                    continue;
                    break;
                case '\n':
                    continue;
                    break;
                default:
                    throw new Exception("Non-integer string given");
                    break;
            };
            val = 10 * val + digit;
        }
        return val;
    }
    
    /** \brief Sorts a list of integers
        \param xs List to be sorted
    */
    public static void selectionSort(List<int> xs) {
        for (int i = 0; i < xs.Count - 1; i += 1) {
            int maxIdx = i;
            for (int j = i + 1; j < xs.Count; j += 1) {
                if (xs[j] < xs[maxIdx]) {
                    maxIdx = j;
                }
            }
            int temp = xs[i];
            xs[i] = xs[maxIdx];
            xs[maxIdx] = temp;
        }
    }
}
