/** \file OOTest.cs
    \author Brandon Bosman
    \date Apr. 24, 2026
    \brief Tests various aspects of general object functionality
    \note Generated by Drasil v0.1-alpha
*/

using System;

public class OOTest {
    
    public static void Main(string[] args) {
        Console.WriteLine(testClass.y);
        testClass testObj = new testClass(56);
        Console.WriteLine(testObj.mulByX(42));
        Console.WriteLine(testClass.square(2.5));
    }
}

/** \brief Basic class to test some stuff
*/
public class testClass {
    public int x;
    public static double y = 17.4;
    
    public testClass(int x) {
        this.x = x;
    }
    
    public int mulByX(int num) {
        return this.x * num;
    }
    
    public static double square(double num) {
        return num * num;
    }
}
