name:                drasil-database
version:             0.1.1.0
author:              "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:          "Jacques Carette"
synopsis:	           A framework for code and document generation for scientific software - Database SubPackage
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- lens
- drasil-lang
- drasil-theory
- drasil-utils

ghc-options:
- -Wall
- -Wredundant-constraints

default-extensions:
  - StrictData

library:
  source-dirs: lib
  exposed-modules:
  - Database.Drasil
  when:
  - condition: false
    other-modules: Paths_drasil_database
