/** \file Control.cpp
    \author Olu Owojaiye
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

#include <string>

#include "InputParameters.hpp"
#include "OutputFormat.hpp"

using std::string;

/** \brief Controls the flow of the program
    \param argc Number of command-line arguments
    \param argv List of command-line arguments
    \return exit code
*/
int main(int argc, const char *argv[]) {
    string filename = argv[1];
    double L_rod;
    double m;
    double α;
    double θ_p;
    double θ_i;
    double p_x^i;
    double p_y^i;
    get_input(filename, L_rod, m, α, θ_p, θ_i);
    derived_values(L_rod, θ_i, p_x^i, p_y^i);
    input_constraints(L_rod, θ_i);
    write_output(θ_p);
    
    return 0;
}
