/** \file InputParameters.hpp
    \author Olu Owojaiye
    \brief Provides the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

#ifndef InputParameters_h
#define InputParameters_h

#include <string>

using std::ifstream;
using std::string;

/** \brief Reads input from a file with the given file name
    \param filename name of the input file
    \param L_rod length of the rod (m)
    \param m mass (kg)
    \param α angular acceleration (rad/s^2)
    \param θ_p displacement angle of the pendulum (rad)
    \param θ_i initial pendulum angle (rad)
*/
void get_input(string filename, double &L_rod, double &m, double &α, double &θ_p, double &θ_i);

/** \brief Calculates values that can be immediately derived from the inputs
    \param L_rod length of the rod (m)
    \param θ_i initial pendulum angle (rad)
    \param p_x^i x-component of initial position (m)
    \param p_y^i y-component of initial position (m)
*/
void derived_values(double L_rod, double θ_i, double &p_x^i, double &p_y^i);

/** \brief Verifies that input values satisfy the physical constraints
    \param L_rod length of the rod (m)
    \param θ_i initial pendulum angle (rad)
*/
void input_constraints(double L_rod, double θ_i);

#endif
