package SglPend;

/** \file Control.java
    \author Olu Owojaiye
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

import java.io.FileNotFoundException;
import java.io.IOException;

public class Control {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void main(String[] args) throws FileNotFoundException, IOException {
        String filename = args[0];
        double L_rod;
        double m;
        double α;
        double θ_p;
        double θ_i;
        double p_x^i;
        double p_y^i;
        Object[] outputs = InputParameters.get_input(filename);
        L_rod = (double)(outputs[0]);
        m = (double)(outputs[1]);
        α = (double)(outputs[2]);
        θ_p = (double)(outputs[3]);
        θ_i = (double)(outputs[4]);
        outputs = InputParameters.derived_values(L_rod, θ_i);
        p_x^i = (double)(outputs[0]);
        p_y^i = (double)(outputs[1]);
        InputParameters.input_constraints(L_rod, θ_i);
        OutputFormat.write_output(θ_p);
    }
}
