.PHONY: all
all:
	cd code && $(MAKE) all
	cd srs && $(MAKE) all
	cd design_doc && $(MAKE) all
    
.PHONY: clean
clean:
	cd code && $(MAKE) clean
	cd srs && $(MAKE) clean
	cd design_doc && $(MAKE) clean