/** \file HelloWorld.hpp
    \author Brandon Bosman
    \brief Advent of Code Day 1
    \note Generated by Drasil v0.1-alpha
*/

#ifndef HelloWorld_h
#define HelloWorld_h

#include <string>
#include <vector>

using std::ifstream;
using std::string;
using std::vector;

/** \brief Converts a string to integer
    \param str String to be converted
    \return Integer value of the string
*/
int strToInt(vector<char> str);

/** \brief Sorts a list of integers
    \param xs List to be sorted
*/
void selectionSort(vector<int> xs);

#endif
