/** main.swift
    Tests various GOOL functions. It should run without errors.
    - Authors: Brooks MacLachlan
    - Note: Generated by Drasil v0.1-alpha
*/

import Foundation

extension String: Error {}

// Initializing variables
var a: Int
var b: Int = 5
var myOtherList: [Double] = [1.0, 1.5]
var oneIndex: Int = myOtherList.firstIndex(of: 1.0)!
print(oneIndex)
a = myOtherList.count
assert( a == 2 , "List size should be 2")
myOtherList.insert(2.0, at: 2)
myOtherList.append(2.5)
var e: Double
e = myOtherList[1]
myOtherList[1] = 17.4
var myName: [String] = []
myName = "Brooks Mac".components(separatedBy: " ")
print(myName)
var boringList: [Bool] = [false, false, false, false, false]
print(boringList)
assert( b == 5 , "b should be 5")
assert( myOtherList.count == 4 , "myOtherList should have 4 elements")
assert( oneIndex == 0 , "oneIndex should be 0")

// List slicing tests
// Create variables for list slices
var mySlicedList: [Double] = []
var mySlicedList2: [Double] = []
var mySlicedList3: [Double] = []
var mySlicedList4: [Double] = []
var mySlicedList5: [Double] = []
var mySlicedList6: [Double] = []
var mySlicedList7: [Double] = []
var mySlicedList8: [Double] = []
var mySlicedList9: [Double] = []
var mySlicedList10: [Double] = []
var mySlicedList11: [Double] = []

// Create some variables for later tests
var x: Int = 3
var y: Int = 1
var z: Int = -1

mySlicedList = [Int](stride(from: 1, to: 3, by: 1)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList2 = [Int](stride(from: 1, to: 4, by: 2)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList3 = [Int](stride(from: 1, to: myOtherList.count, by: 1)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList4 = [Int](stride(from: 3, to: 1, by: 1)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList5 = [Int](stride(from: 3, to: 1, by: -1)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList6 = [Int](stride(from: myOtherList.count - 1, to: 1, by: -1)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList7 = [Int](stride(from: 3, to: -1, by: -1)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList8 = [Int](stride(from: 3, to: 0, by: z)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList9 = [Int](stride(from: x, to: y, by: z)).map({(i: Int) -> Double in myOtherList[i]})

var endIdx: Int = z > 0 ? myOtherList.count : -1
mySlicedList10 = [Int](stride(from: 2, to: endIdx, by: z)).map({(i: Int) -> Double in myOtherList[i]})

var endIdx0: Int = z > 0 ? myOtherList.count : -1
mySlicedList10 = [Int](stride(from: 2, to: endIdx0, by: z)).map({(i: Int) -> Double in myOtherList[i]})

mySlicedList11 = [Int](stride(from: y, to: x, by: z)).map({(i: Int) -> Double in myOtherList[i]})

// Print results of list slicing tests
print("")
print("List slicing:")
print("myOtherList: ", terminator: "")
print(myOtherList)
print("mySlicedList: ", terminator: "")
print(mySlicedList)
print("mySlicedList2: ", terminator: "")
print(mySlicedList2)
print("mySlicedList3: ", terminator: "")
print(mySlicedList3)
print("mySlicedList4: ", terminator: "")
print(mySlicedList4)
print("mySlicedList5: ", terminator: "")
print(mySlicedList5)
print("mySlicedList6: ", terminator: "")
print(mySlicedList6)
print("mySlicedList7: ", terminator: "")
print(mySlicedList7)
print("mySlicedList8: ", terminator: "")
print(mySlicedList8)
print("mySlicedList9: ", terminator: "")
print(mySlicedList9)
print("mySlicedList10: ", terminator: "")
print(mySlicedList10)
print("mySlicedList11: ", terminator: "")
print(mySlicedList11)

print("")
if b >= 6 {
    var dummy: String = "dummy"
}
else if b == 5 {
    // If body ----------------------------------------------------------------
    var c: Int
    var d: Int
    a = 5
    b = a + 2
    c = b + 3
    d = b
    d -= a
    c -= d
    b += 17;
    c += 17;
    a += 1;
    d += 1;
    c -= 1
    b -= 1
    var myList: [Int] = []
    var myObj: Character = "o"
    let myConst: String = "Imconstant"
    print(myConst)
    print(a)
    print(b)
    print(c)
    print(d)
    print(myOtherList)
    print(mySlicedList)
    print("Type an int")
    d = Int(readLine()!)!
    print("Type another")
    readLine()!
    
    print(" too")
    print("boo", terminator: "")
    print(true, terminator: "")
    print(0, terminator: "")
    print("c", terminator: "")
    print(!(true))
    print(-1)
    print(sqrt(4.0))
    print(abs(-4))
    print(log10(2.0))
    print(log(2.0))
    print(exp(-2.0))
    print(sin(2.0))
    print(cos(2.0))
    print(tan(2.0))
    print(tan(2.0))
    print(true && false)
    print(true || false)
    print(true && !(false))
    print(!(true && true))
    print(6 + 2)
    print(6 - 2)
    print(6 * 2)
    print(6 / 2)
    print(6 % 4)
    print(Int(pow(Double(6), Double(2))))
    print(6 + 2 * 3)
    print(1.0 / sin(1.0))
    print(1.0 / cos(1.0))
    print(a)
    print(true ? 5 : 0)
    print(1.0 / tan(1.0))
    // End If body ------------------------------------------------------------
}
else {
    print(CommandLine.arguments[5])
}
if boringList != nil {
    print("Ew, boring list!")
}
else {
    print("Great, no bores!")
}
switch a {
    case 5:
        b = 10
    case 0:
        b = 5
    default:
        b = 0
};
for i in [Int](stride(from: 0, to: 9, by: 1)) {
    print(i)
}
while a < 13 {
    print("Hello")
    a += 1;
}
for num in myOtherList {
    print(doubleAndAdd(num, 1.0))
}
do {
    throw "Good-bye!"
} catch {
    print("Caught intentional error")
}
