/** \file Calculations.hpp
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef Calculations_h
#define Calculations_h

#include <string>

using std::string;

/** \brief Calculates flight duration (s)
    \param v_launch launch speed (m/s)
    \param theta launch angle (rad)
    \param g magnitude of gravitational acceleration (m/s^2)
    \return flight duration (s)
*/
float func_t_flight(float v_launch, float theta, float g);

/** \brief Calculates landing position (m)
    \param v_launch launch speed (m/s)
    \param theta launch angle (rad)
    \param g magnitude of gravitational acceleration (m/s^2)
    \return landing position (m)
*/
float func_p_land(float v_launch, float theta, float g);

/** \brief Calculates distance between the target position and the landing position (m)
    \param p_target target position (m)
    \param p_land landing position (m)
    \return distance between the target position and the landing position (m)
*/
float func_d_offset(float p_target, float p_land);

/** \brief Calculates output message as a string
    \param p_target target position (m)
    \param epsilon hit tolerance
    \param d_offset distance between the target position and the landing position (m)
    \return output message as a string
*/
string func_s(float p_target, float epsilon, float d_offset);

#endif
