/** \file OOTest.hpp
    \author Brandon Bosman
    \date Apr. 24, 2026
    \brief Tests various aspects of general object functionality
    \note Generated by Drasil v0.1-alpha
*/

#ifndef OOTest_h
#define OOTest_h

/** \brief Basic class to test some stuff
*/
class testClass {
    public:
        int x;
        static double y;
        
        testClass(int x);
        int mulByX(int num);
        double square(double num);
};

#endif
