/** \file Control.cpp
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief Controls the flow of the program
    \note Generated by Drasil v0.1-alpha
*/

#include <string>

#include "Calculations.hpp"
#include "InputParameters.hpp"
#include "OutputFormat.hpp"

using std::string;

/** \brief Controls the flow of the program
    \param argc Number of command-line arguments
    \param argv List of command-line arguments
    \return exit code
*/
int main(int argc, const char *argv[]) {
    string filename = argv[1];
    float g = 9.8f;
    float epsilon = 2.0e-2f;
    float v_launch;
    float theta;
    float p_target;
    get_input(filename, v_launch, theta, p_target);
    input_constraints(v_launch, theta, p_target);
    float t_flight = func_t_flight(v_launch, theta, g);
    float p_land = func_p_land(v_launch, theta, g);
    float d_offset = func_d_offset(p_target, p_land);
    string s = func_s(p_target, epsilon, d_offset);
    write_output(s, d_offset, t_flight);
    
    return 0;
}
