name:        drasil-lang
version:     0.1.60.0
author:      "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:  "Jacques Carette"
synopsis:	   A framework for code and document generation for scientific software - Language SubPackage
github:      JacquesCarette/Drasil
homepage:    https://jacquescarette.github.io/Drasil/
description: Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- lens
- split
- Decimal
- unicode-names >= 3.2.0.0
- drasil-utils
- containers

ghc-options:
- -Wall
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - Language.Drasil
  - Language.Drasil.Chunk.Concept.NamedCombinators
  - Language.Drasil.Development
  - Language.Drasil.Display
  - Language.Drasil.Expr.Development
  - Language.Drasil.Literal.Development
  - Language.Drasil.ModelExpr.Development
  - Language.Drasil.CodeExpr.Development
  - Language.Drasil.CodeExpr
  - Language.Drasil.NounPhrase.Combinators
  - Language.Drasil.Sentence.Combinators
  - Language.Drasil.ShortHands
  when:
  - condition: false
    other-modules: Paths_drasil_lang
