## \file HelloWorld.py
# \author Brandon Bosman
# \brief Advent of Code Day 1
# \note Generated by Drasil v0.1-alpha

## \brief Converts a string to integer
# \param str String to be converted
# \return Integer value of the string
def strToInt(str):
    val = 0
    for i in range(0, len(str), 1):
        if str[i] == '0':
            digit = 0
        elif str[i] == '1':
            digit = 1
        elif str[i] == '2':
            digit = 2
        elif str[i] == '3':
            digit = 3
        elif str[i] == '4':
            digit = 4
        elif str[i] == '5':
            digit = 5
        elif str[i] == '6':
            digit = 6
        elif str[i] == '7':
            digit = 7
        elif str[i] == '8':
            digit = 8
        elif str[i] == '9':
            digit = 9
        elif str[i] == ' ':
            continue
        elif str[i] == '\n':
            continue
        else:
            raise Exception("Non-integer string given")
        val = 10 * val + digit
    return val

## \brief Sorts a list of integers
# \param xs List to be sorted
def selectionSort(xs):
    for i in range(0, len(xs) - 1, 1):
        maxIdx = i
        for j in range(i + 1, len(xs), 1):
            if xs[j] < xs[maxIdx]:
                maxIdx = j
        temp = xs[i]
        xs[i] = xs[maxIdx]
        xs[maxIdx] = temp

# Get input
filePath = "../../../../drasil-code/test/input.txt"
fileHandle = open(filePath, "r")
fileContents = fileHandle.readlines()
fileHandle.close()

# Process input
list1 = []
list2 = []
for line in fileContents:
    splitLine = line.split(" ")
    list1.append(strToInt(splitLine[0]))
    list2.append(strToInt(splitLine[3]))
selectionSort(list1)
selectionSort(list2)

# Calculate distance and print out
distance = 0
for i in range(0, len(list1), 1):
    partDistance = list1[i] - list2[i]
    if partDistance < 0:
        partDistance = -partDistance
    distance += partDistance;
print("Distance: ", end="")
print(distance)
