/** \file InputParameters.hpp
    \author Nikitha Krithnan and W. Spencer Smith
    \brief Provides the structure for holding input values, the function for reading inputs, the function for calculating derived values, and the function for checking the physical constraints and software constraints on the input
    \note Generated by Drasil v0.1-alpha
*/

#ifndef InputParameters_h
#define InputParameters_h

#include <set>
#include <string>

using std::ifstream;
using std::ofstream;
using std::set;
using std::string;

/** \brief Structure for holding the input values and derived values
*/
class InputParameters {
    public:
        double a;
        double b;
        double w;
        double P_btol;
        double TNT;
        string g;
        double t;
        double SD_x;
        double SD_y;
        double SD_z;
        double h;
        double LDF;
        double GTF;
        double SD;
        double AR;
        double w_TNT;
        
        /** \brief Initializes input object by reading inputs, calculating derived values, and checking physical constraints and software constraints on the input
            \param filename name of the input file
        */
        InputParameters(string filename);
    
    private:
        /** \brief Reads input from a file with the given file name
            \param filename name of the input file
        */
        void get_input(string filename);
        /** \brief Calculates values that can be immediately derived from the inputs
        */
        void derived_values();
        /** \brief Verifies that input values satisfy the physical constraints and software constraints
        */
        void input_constraints();
};

#endif
