/** \file OutputFormat.hpp
    \author Nikitha Krithnan and W. Spencer Smith
    \brief Provides the function for writing outputs
    \note Generated by Drasil v0.1-alpha
*/

#ifndef OutputFormat_h
#define OutputFormat_h

#include <string>

using std::ofstream;
using std::string;

/** \brief Writes the output values to output.txt
    \param isSafePb probability of glass breakage safety requirement
    \param isSafeLR 3 second load equivalent resistance safety requirement
    \param P_b probability of breakage
    \param J stress distribution factor (Function)
*/
void write_output(bool isSafePb, bool isSafeLR, double P_b, double J);

#endif
