package Projectile;

/** \file Calculations.java
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief Provides functions for calculating the outputs
    \note Generated by Drasil v0.1-alpha
*/

public class Calculations {
    
    /** \brief Calculates flight duration (s)
        \param v_launch launch speed (m/s)
        \param theta launch angle (rad)
        \param g magnitude of gravitational acceleration (m/s^2)
        \return flight duration (s)
    */
    public static float func_t_flight(float v_launch, float theta, float g) {
        return 2.0f * v_launch * (float)(Math.sin(theta)) / g;
    }
    
    /** \brief Calculates landing position (m)
        \param v_launch launch speed (m/s)
        \param theta launch angle (rad)
        \param g magnitude of gravitational acceleration (m/s^2)
        \return landing position (m)
    */
    public static float func_p_land(float v_launch, float theta, float g) {
        return 2.0f * (float)(Math.pow(v_launch, 2.0f)) * (float)(Math.sin(theta)) * (float)(Math.cos(theta)) / g;
    }
    
    /** \brief Calculates distance between the target position and the landing position (m)
        \param p_target target position (m)
        \param p_land landing position (m)
        \return distance between the target position and the landing position (m)
    */
    public static float func_d_offset(float p_target, float p_land) {
        return p_land - p_target;
    }
}
