""" OutputFormat.jl
    Provides the function for writing outputs
    - Authors: Thulasi Jegatheesan
    - Note: Generated by Drasil v0.1-alpha
"""

module OutputFormat

""" Writes the output values to output.txt
    - Parameter E_W: change in heat energy in the water: change in thermal energy within the water (J)
    - Parameter T_W: temperature of the water: the average kinetic energy of the particles within the water (degreeC)
"""
function write_output(E_W::Float64, T_W::Array{Float64})
    outputfile = open("output.txt", "w")
    print(outputfile, "T_W = ")
    println(outputfile, T_W)
    print(outputfile, "E_W = ")
    println(outputfile, E_W)
    close(outputfile)
end

end
