build: Projectile/Control.class

Projectile/Control.class: Projectile/Control.java Projectile/InputParameters.java Projectile/InputConstraints.java Projectile/InputFormat.java Projectile/OutputFormat.java Projectile/Calculations.java
	javac Projectile/Control.java

run: build
	java Projectile.Control $(RUNARGS)

.PHONY: build run
