package Projectile;

/** \file Projectile.java
    \author Samuel J. Crawford, Brooks MacLachlan, and W. Spencer Smith
    \brief A program to predict whether a launched projectile hits its target.
    \note Generated by Drasil v0.1-alpha
*/

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

public class Projectile {
    
    /** \brief Controls the flow of the program
        \param args List of command-line arguments
    */
    public static void main(String[] args) throws FileNotFoundException, IOException {
        PrintWriter outfile;
        String filename = args[0];
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 'filename' assigned ");
        outfile.print(filename);
        outfile.println(" in module Projectile");
        outfile.close();
        InputParameters inParams = new InputParameters(filename);
        float t_flight = func_t_flight(inParams);
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 't_flight' assigned ");
        outfile.print(t_flight);
        outfile.println(" in module Projectile");
        outfile.close();
        float p_land = func_p_land(inParams);
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 'p_land' assigned ");
        outfile.print(p_land);
        outfile.println(" in module Projectile");
        outfile.close();
        float d_offset = func_d_offset(inParams, p_land);
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 'd_offset' assigned ");
        outfile.print(d_offset);
        outfile.println(" in module Projectile");
        outfile.close();
        write_output(d_offset, t_flight);
    }
    
    /** \brief Calculates flight duration (s)
        \param inParams structure holding the input values
        \return flight duration (s)
    */
    public static float func_t_flight(InputParameters inParams) throws IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function func_t_flight called with inputs: {");
        outfile.print("  inParams = ");
        outfile.println("Instance of InputParameters object");
        outfile.println("  }");
        outfile.close();
        
        return 2.0f * inParams.v_launch * (float)(Math.sin(inParams.theta)) / inParams.g;
    }
    
    /** \brief Calculates landing position (m)
        \param inParams structure holding the input values
        \return landing position (m)
    */
    public static float func_p_land(InputParameters inParams) throws IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function func_p_land called with inputs: {");
        outfile.print("  inParams = ");
        outfile.println("Instance of InputParameters object");
        outfile.println("  }");
        outfile.close();
        
        return 2.0f * (float)(Math.pow(inParams.v_launch, 2.0f)) * (float)(Math.sin(inParams.theta)) * (float)(Math.cos(inParams.theta)) / inParams.g;
    }
    
    /** \brief Calculates distance between the target position and the landing position (m)
        \param inParams structure holding the input values
        \param p_land landing position (m)
        \return distance between the target position and the landing position (m)
    */
    public static float func_d_offset(InputParameters inParams, float p_land) throws IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function func_d_offset called with inputs: {");
        outfile.print("  inParams = ");
        outfile.print("Instance of InputParameters object");
        outfile.println(", ");
        outfile.print("  p_land = ");
        outfile.println(p_land);
        outfile.println("  }");
        outfile.close();
        
        return p_land - inParams.p_target;
    }
    
    /** \brief Writes the output values to output.txt
        \param d_offset distance between the target position and the landing position (m)
        \param t_flight flight duration (s)
    */
    public static void write_output(float d_offset, float t_flight) throws IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function write_output called with inputs: {");
        outfile.print("  d_offset = ");
        outfile.print(d_offset);
        outfile.println(", ");
        outfile.print("  t_flight = ");
        outfile.println(t_flight);
        outfile.println("  }");
        outfile.close();
        
        PrintWriter outputfile;
        outputfile = new PrintWriter(new FileWriter(new File("output.txt"), false));
        outputfile.print("d_offset = ");
        outputfile.println(d_offset);
        outputfile.print("t_flight = ");
        outputfile.println(t_flight);
        outputfile.close();
    }
}

/** \brief Structure for holding the input values and constant values
*/
class InputParameters {
    public float v_launch;
    public float theta;
    public float p_target;
    public float g = 9.8f;
    public float epsilon = 2.0e-2f;
    
    /** \brief Initializes input object by reading inputs and checking physical constraints on the input
        \param filename name of the input file
    */
    public InputParameters(String filename) throws FileNotFoundException, IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function InputParameters called with inputs: {");
        outfile.print("  filename = ");
        outfile.println(filename);
        outfile.println("  }");
        outfile.close();
        
        this.get_input(filename);
        this.input_constraints();
    }
    
    /** \brief Reads input from a file with the given file name
        \param filename name of the input file
    */
    private void get_input(String filename) throws FileNotFoundException, IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function get_input called with inputs: {");
        outfile.print("  filename = ");
        outfile.println(filename);
        outfile.println("  }");
        outfile.close();
        
        Scanner infile;
        infile = new Scanner(new File(filename));
        infile.nextLine();
        this.v_launch = Float.parseFloat(infile.nextLine());
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 'this.v_launch' assigned ");
        outfile.print(this.v_launch);
        outfile.println(" in module Projectile");
        outfile.close();
        infile.nextLine();
        this.theta = Float.parseFloat(infile.nextLine());
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 'this.theta' assigned ");
        outfile.print(this.theta);
        outfile.println(" in module Projectile");
        outfile.close();
        infile.nextLine();
        this.p_target = Float.parseFloat(infile.nextLine());
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.print("var 'this.p_target' assigned ");
        outfile.print(this.p_target);
        outfile.println(" in module Projectile");
        outfile.close();
        infile.close();
    }
    
    /** \brief Verifies that input values satisfy the physical constraints
    */
    private void input_constraints() throws IOException {
        PrintWriter outfile;
        outfile = new PrintWriter(new FileWriter(new File("log.txt"), true));
        outfile.println("function input_constraints called with inputs: {");
        outfile.println("  }");
        outfile.close();
        
        if (!(this.v_launch > 0.0f)) {
            System.out.print("Warning: ");
            System.out.print("v_launch has value ");
            System.out.print(this.v_launch);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0f);
            System.out.println(".");
        }
        if (!(0.0f < this.theta && this.theta < Math.PI / 2.0f)) {
            System.out.print("Warning: ");
            System.out.print("theta has value ");
            System.out.print(this.theta);
            System.out.print(", but is suggested to be ");
            System.out.print("between ");
            System.out.print(0.0f);
            System.out.print(" and ");
            System.out.print(Math.PI / 2.0f);
            System.out.print(" ((pi)/(2))");
            System.out.println(".");
        }
        if (!(this.p_target > 0.0f)) {
            System.out.print("Warning: ");
            System.out.print("p_target has value ");
            System.out.print(this.p_target);
            System.out.print(", but is suggested to be ");
            System.out.print("above ");
            System.out.print(0.0f);
            System.out.println(".");
        }
    }
}
