on:
  push:
    branches: main
    paths: [code/**, .github/workflows/Deploy.yaml]
  workflow_dispatch:
name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
defaults:
  run:
    shell: bash
    working-directory: code
jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: "Update apt package list"
        run: |
          sudo apt-get update

      - name: "Install requirements"
        run: |
          sudo apt-get install -y graphviz

      - name: "Cache dependencies"
        uses: actions/cache@v6
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('code/stack.yaml') }}

      - name: "Install dependencies"
        run: make stackArgs="--no-terminal" deps

      - name: "Build"
        run: make code stackArgs="--no-terminal" GHCFLAGS="-Werror -Wwarn=deprecations"

      - name: "Stack Test"
        run: make stack_test stackArgs="--no-terminal"

      - name: "Test built artifacts against stable"
        run: make stackArgs="--no-terminal" GHCFLAGS="-Werror -Wwarn=deprecations" NOISY=yes

      - name: "Generate module dependency graphs"
        run: make graphs

      - name: "Analyze Drasil code"
        run: make analysis

      - name: "Convert analysis graphs into dot and circo SVGs"
        run: make convertAnalyzed

      - name: "Upload generated artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: generated
          path: code/build
          include-hidden-files: true

      - name: "Upload gooltest artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: generated-gooltest
          path: code/drasil-code/test/build

      - name: "Compress website artifacts"
        run: tar zcf $RUNNER_TEMP/website-artifacts.tar.gz analysis graphs website

      - name: "Upload website artifacts"
        uses: actions/upload-artifact@v7
        with:
          path: ${{ runner.temp }}/website-artifacts.tar.gz
          archive: false

      - name: "Cache stack work"
        uses: actions/cache/save@v6
        with:
          path: |
            code/.stack-work
            code/**/.stack-work
            code/**/.hie
          key: ${{ runner.os }}-stack-work

  haddock:
    name: Haddock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: "Restore dependency cache"
        uses: actions/cache/restore@v6
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('code/stack.yaml') }}

      - name: "Generate Haddock docs (full + std)"
        run: make docs FULL=1

      - name: "Upload Haddock docs"
        uses: actions/upload-artifact@v7
        with:
          name: haddock-docs
          path: code/docs

      - name: "Cache stack work"
        uses: actions/cache/save@v6
        with:
          path: |
            code/.stack-work
            code/**/.stack-work
            code/**/.hie
          key: ${{ runner.os }}-stack-work-haddock

  gooltest:
    name: "Compile GOOL"
    needs: build
    runs-on: ubuntu-latest
    env:
      SKIP_GEN: 1
    steps:
      - uses: actions/checkout@v7

      - name: "Update apt package list"
        run: |
          sudo apt-get update

      - name: "Install requirements"
        run: |
          sudo apt-get install -y default-jdk-headless mono-devel

      - name: "Download generated artifacts"
        uses: actions/download-artifact@v8
        with:
          name: generated
          path: code/build

      - name: "Download gooltest artifacts"
        uses: actions/download-artifact@v8
        with:
          name: generated-gooltest
          path: code/drasil-code/test/build

      - name: "Compile GOOL Examples"
        run: make codegenTest
      
      - name: "Compile generated software artifacts"
        run: make gool

  generate:
    name: "Generate Documents"
    needs: build
    runs-on: ubuntu-26.04
    env:
      SKIP_GEN: 1
    steps:
      - uses: actions/checkout@v7

      - name: "Update apt package list"
        run: |
          sudo apt-get update

      - name: "Install requirements"
        run: |
          sudo apt-get install -y graphviz fonts-lmodern texlive-bibtex-extra texlive-latex-extra texlive-science texlive-luatex inkscape jupyter-nbconvert doxygen

      - name: "Install mdBook"
        env:
          MDBOOK_VERSION: 0.5.4
        working-directory: ${{ runner.temp }}
        run: |
          curl -L -O https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz
          tar zxf mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz
          mkdir -p ~/.local/bin
          mv mdbook ~/.local/bin
          mdbook --version

      - name: "Download generated artifacts"
        uses: actions/download-artifact@v8
        with:
          name: generated
          path: code/build

      - name: "Compile generated TeX artifacts"
        run: make -j4 tex SUMMARIZE_TEX=yes

      - name: "Build mdBook Examples"
        run: make mdbook_build

      - name: "Extract HTML copies of Jupyter Notebooks"
        run: make jupyter_html

      - name: "Create Doxygen for generated software artifacts"
        run: make doxygen

      - name: "Upload full generated artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: generated-full
          path: code/build

  prepare_deploy:
    name: "Prepare Deployment"
    needs: [haddock, generate]
    runs-on: ubuntu-latest
    env:
      SKIP_GEN: 1
    steps:
      - uses: actions/checkout@v7

      - name: "Download full generated artifacts"
        uses: actions/download-artifact@v8
        with:
          name: generated-full
          path: code/build

      - name: "Download Haddock docs"
        uses: actions/download-artifact@v8
        with:
          name: haddock-docs
          path: code/docs

      - name: "Download website artifacts"
        uses: actions/download-artifact@v8
        with:
          name: website-artifacts.tar.gz
          path: ${{ runner.temp }}

      - name: "Extract website artifacts"
        run: tar zxf $RUNNER_TEMP/website-artifacts.tar.gz

      - name: "Prepare full website deployment environment"
        run: make deploy_lite

      - name: "Upload static website as artifact"
        uses: actions/upload-pages-artifact@v5
        with:
          path: code/deploy

  deploy:
    name: "Deploy"
    needs: prepare_deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
