spec-version: 0.36.0
name:         drasil-build-artifacts
version:      0.1.1.0
author:       "Dan Szymczak, Steven Palmer, Jacques Carette, Spencer Smith"
maintainer:   "Jacques Carette"
synopsis:     A framework for code and document generation for scientific software - build-artifacts SubPackage
github:       JacquesCarette/Drasil
homepage:     https://jacquescarette.github.io/Drasil/
description:  Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

language: Haskell2010
default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- ImportQualifiedPost
- StrictData

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- pretty
- prettyprinter
- template-haskell

ghc-options:
- -Wall
- -Wredundant-constraints
- -Wmissing-export-lists

library:
  source-dirs: lib
  exposed-modules:
  - Drasil.Build.Artifacts
